(load "lib/aima/utilities.lisp")
(load "lib/aima/binary-tree.lisp")
(load "lib/aima/queue.lisp")
(load "lib/aima/cltl2.lisp")
(load "lib/aima/basic-env.lisp")
(load "lib/aima/grid-env.lisp")
(load "lib/aima/agent.lisp")
(load "lib/aima/grid.lisp")
